# Generated by Django 2.0.7 on 2018-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180711_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='product'),
        ),
    ]
