# Generated by Django 2.0.7 on 2018-07-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=140)),
                ('tagline', models.CharField(max_length=140, null=True)),
                ('icon', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=140, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webapp.Categ')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'date')},
        ),
    ]
