# Generated by Django 2.0.7 on 2018-07-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180708_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='product',
            new_name='product_id',
        ),
    ]
