# Generated by Django 2.0.7 on 2018-07-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180708_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
    ]
