# Generated by Django 2.0.7 on 2018-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20180708_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='FileUploader', upload_to='product'),
        ),
    ]
