# Generated by Django 2.0.7 on 2018-07-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_ammount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='product'),
        ),
        migrations.AddField(
            model_name='trade',
            name='desired_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_product', to='webapp.Product'),
        ),
        migrations.AddField(
            model_name='trade',
            name='offered_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_product', to='webapp.Product'),
        ),
    ]
