# Generated by Django 2.0.7 on 2018-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categ',
            name='icon',
        ),
        migrations.AddField(
            model_name='categ',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='categories'),
        ),
    ]
