# Generated by Django 2.0.7 on 2018-07-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180709_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ',
            old_name='image',
            new_name='icon',
        ),
    ]
