# Generated by Django 2.0.7 on 2018-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20180712_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='desired_product_title',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='trade',
            name='offered_product_title',
            field=models.CharField(default='', max_length=140),
        ),
    ]
