# Generated by Django 2.0.7 on 2018-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20180712_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
