# Generated by Django 2.0.7 on 2018-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_comment_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender_image',
            field=models.CharField(default='noimage.jpg', max_length=140),
        ),
    ]
