# Generated by Django 2.0.7 on 2018-07-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20180713_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='for_product',
            new_name='product',
        ),
    ]
