# Generated by Django 2.0.7 on 2018-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20180713_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sender_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
