# Generated by Django 2.0.7 on 2018-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_offer_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
