# Generated by Django 2.0.7 on 2018-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20180713_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='new', max_length=140),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='no', max_length=140),
        ),
    ]
