# Generated by Django 2.0.7 on 2018-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20180715_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
    ]
