# Generated by Django 2.0.7 on 2018-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='sell', max_length=140),
        ),
    ]
